global:
  scrape_interval:     15s 

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # neo4j
  - job_name: 'neo4j'
    scrape_interval: 5s
    static_configs:
    - targets: ['10.160.1.101:2004']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

